/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-23 10:40:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import ServersidePackages.DataObject;

public final class employee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ServersidePackages.DataObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 String loggedInUsername = (String) request.getAttribute("loggedInUsername"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <!-- Basic -->\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("  <!-- Mobile Metas -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Site Metas -->\n");
      out.write("  <meta name=\"keywords\" content=\"\" />\n");
      out.write("  <meta name=\"description\" content=\"\" />\n");
      out.write("  <meta name=\"author\" content=\"\" />\n");
      out.write("\n");
      out.write("  <title>Fonicy</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- bootstrap core css -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\n");
      out.write("\n");
      out.write("  <!-- fonts style -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!--owl slider stylesheet -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" />\n");
      out.write("\n");
      out.write("  <!-- font awesome style -->\n");
      out.write("  <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- responsive style -->\n");
      out.write("  <link href=\"css/responsive.css\" rel=\"stylesheet\" />\n");
      out.write("  \n");
      out.write("  <link href=\"css/employee.css\" rel=\"stylesheet\" />\n");
      out.write("  \n");
      out.write("  <style>\n");
      out.write("      .all_emp{\n");
      out.write("          display: flex;\n");
      out.write("      }\n");
      out.write("  </style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <div class=\"hero_area\">\n");
      out.write("    <!-- header section strats -->\n");
      out.write("    <header class=\"header_section\">\n");
      out.write("      <div class=\"header_top\">\n");
      out.write("        <div class=\"container-fluid header_top_container\">\n");
      out.write("          <div class=\"lang_box dropdown\">\n");
      out.write("            <a href=\"#\" title=\"Language\" class=\"nav-link\" data-toggle=\"dropdown\" aria-expanded=\"true\">\n");
      out.write("              <img src=\"images/flag-uk.png\" alt=\"flag\" class=\" \" title=\"United Kingdom\"> <i class=\"fa fa-angle-down \" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"dropdown-menu \">\n");
      out.write("              <a href=\"#\" class=\"dropdown-item\">\n");
      out.write("                <img src=\"images/flag-france.png\" class=\"\" alt=\"flag\">\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("            <span>\n");
      out.write("              English\n");
      out.write("            </span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"contact_nav\">\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Call : +01 123455678990\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Email : demo@gmail.com\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Location\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"social_box\">\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-facebook\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-instagram\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"header_bottom\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <nav class=\"navbar navbar-expand-lg custom_nav-container \">\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write("              <img src=\"images/logo.png\" alt=\"\">\n");
      out.write("            </a>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("              <span class=\"\"> </span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("              <ul class=\"navbar-nav  \">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"company.jsp\">Company Info <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item active\">\n");
      out.write("                  <a class=\"nav-link\" href=\"#\" onclick=\"gotoEmployeeInfo()\">Employees Info</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"client.jsp\"> Client Info</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"project.jsp\">Project Info</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"transport.jsp\">Transport Info</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"merchant.jsp\">Merchant Info</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.jsp\"> Log Out</a>\n");
      out.write("                </li>\n");
      out.write("                <form class=\"form-inline\">\n");
      out.write("                  <button class=\"btn  my-2 my-sm-0 nav_search-btn\" type=\"submit\">\n");
      out.write("                    <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\n");
      out.write("                  </button>\n");
      out.write("                </form>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"quote_btn-container\">\n");
      out.write("                <a href=\"\" class=\"quote_btn\">\n");
      out.write("                  Get A Quote\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("            </div>            \n");
      out.write("          </nav>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- end header section -->\n");
      out.write("     <!-- main section -->\n");
      out.write("     <div class=\"employee_container\" >\n");
      out.write("         <div class=\"sidebar\">\n");
      out.write("             <button onclick=\"showAddEmplyee()\">Add Employees</button><br><br>\n");
      out.write("             <button onclick=\"showEmplyee()\">Show Employees</button><br><br>\n");
      out.write("             <button>Add Employees</button><br><br>\n");
      out.write("             <button>Add Employees</button><br><br>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"workarea\" style=\"flex: 1;\">\n");
      out.write("             <section id=\"initial-section\" class=\"initial-section\"></section>\n");
      out.write("             <section id=\"add-employee\" class=\"add-employee\">\n");
      out.write("                 <div class=\"emp_container\">\n");
      out.write("        <h2>Employee Registration</h2>\n");
      out.write("\n");
      out.write("        <form action=\"AdminServlet?id=emp_reg\" method=\"post\">\n");
      out.write("                    <div class=\"fields\">\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Full Name</label>\n");
      out.write("                            <input type=\"text\" name=\"fullname\" placeholder=\"Enter your name\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Date of Birth</label>\n");
      out.write("                            <input type=\"date\" name=\"dob\" placeholder=\"Enter birth date\" required>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Gender</label>\n");
      out.write("                            <select name=\"gender\" required>\n");
      out.write("                                <option disabled selected>Select gender</option>\n");
      out.write("                                <option>Male</option>\n");
      out.write("                                <option>Female</option>\n");
      out.write("                                <option>Others</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Email</label>\n");
      out.write("                            <input id=\"email\" type=\"text\" name=\"email\" placeholder=\"Enter your email\" oninput=\"autofillUsername()\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Mobile Number</label>\n");
      out.write("                            <input type=\"number\" name=\"mobile\" placeholder=\"Enter mobile number\" required>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                         <div class=\"input-field\">\n");
      out.write("                            <label>ID Type</label>\n");
      out.write("                            <select name=\"idtype\" required>\n");
      out.write("                                <option disabled selected>Select ID Type</option>\n");
      out.write("                                <option>Adhar Card</option>\n");
      out.write("                                <option>Pan Card</option>\n");
      out.write("                                <option>Passport</option>\n");
      out.write("                                <option>Driving License</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>ID Number</label>\n");
      out.write("                            <input type=\"number\" name=\"idnumber\" placeholder=\"Enter ID number\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        \n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Designation</label>\n");
      out.write("                            <select name=\"designation\" required>\n");
      out.write("                                <option disabled selected>Select designation</option>\n");
      out.write("                                <option>Manager</option>\n");
      out.write("                                <option>Supervisor</option>\n");
      out.write("                                <option>Accountant</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Salary</label>\n");
      out.write("                            <input type=\"text\" name=\"salary\" placeholder=\"Enter salary\" required>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Current Address</label>\n");
      out.write("                            <textarea id=\"current-address\" name=\"current-address\" placeholder=\"Enter current address\" rows=\"5\" cols=\"50\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Permanent Address</label>\n");
      out.write("                            <textarea id=\"permanent-address\" name=\"permanent-address\" placeholder=\"Enter current address\" rows=\"5\" cols=\"50\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Employee Username</label>\n");
      out.write("                            <input id=\"empusername\" type=\"text\" name=\"empusername\" placeholder=\"Employee Username\" required readonly>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <label>Employee Password</label>\n");
      out.write("                            <input id=\"empusername\" type=\"password\" name=\"emppassword\" placeholder=\"Enter Temporery Password\" required>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                     </div>   \n");
      out.write("                    \n");
      out.write("                <div type=\"reset\" class=\"buttons\">\n");
      out.write("                        <div class=\"backBtn\">\n");
      out.write("                            <i class=\"uil uil-navigator\"></i>\n");
      out.write("                            <span class=\"btnText\">Back</span>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    <button type=\"submit\" class=\"sumbit\">\n");
      out.write("                            <span class=\"btnText\">Submit</span>\n");
      out.write("                            <i class=\"uil uil-navigator\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("             </section>\n");
      out.write("             <section id=\"show-employee\" class=\"add-employee\">\n");
      out.write("                 \n");
      out.write("        <div class=\"all_emp\">\n");
      out.write("            \n");
      out.write("                <table class=\"emp_table\" border=\"3\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("                <th>Employee UserName</th>\n");
      out.write("                <th>Employee Name</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("            ");

            List<DataObject> dataList = (List<DataObject>) request.getAttribute("dataList");
            for (DataObject data : dataList) { 
            
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( data.getUsername() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( data.getEmpname() );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("        </div>\n");
      out.write("        </section>\n");
      out.write("         </div>\n");
      out.write("             \n");
      out.write("         </div>\n");
      out.write("     </div>\n");
      out.write("     <!-- End main section -->\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <!-- info section -->\n");
      out.write("  <section class=\"info_section \">\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"contact_nav\">\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Call : +01 123455678990\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Email : demo@gmail.com\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Location\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"info_top \">\n");
      out.write("        <div class=\"row info_main_row\">\n");
      out.write("          <div class=\"col-sm-6 col-md-4 col-lg-3\">\n");
      out.write("            <div class=\"info_links\">\n");
      out.write("              <h4>\n");
      out.write("                QUICK LINKS\n");
      out.write("              </h4>\n");
      out.write("              <div class=\"info_links_menu\">\n");
      out.write("                <a class=\"\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                <a class=\"\" href=\"service.jsp\">Services</a>\n");
      out.write("                <a class=\"\" href=\"about.jsp\"> About</a>\n");
      out.write("                <a class=\"\" href=\"project.jsp\">Project</a>\n");
      out.write("                <a class=\"\" href=\"testimonial.jsp\">Testimonial</a>\n");
      out.write("                <a class=\"\" href=\"contact.jsp\">Contact Us</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-sm-6 col-md-4 col-lg-3 mx-auto\">\n");
      out.write("            <div class=\"info_post\">\n");
      out.write("              <h5>\n");
      out.write("                INSTAGRAM FEEDS\n");
      out.write("              </h5>\n");
      out.write("              <div class=\"post_box\">\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <div class=\"info_form\">\n");
      out.write("              <h4>\n");
      out.write("                SIGN UP TO OUR NEWSLETTER\n");
      out.write("              </h4>\n");
      out.write("              <form action=\"\">\n");
      out.write("                <input type=\"text\" placeholder=\"Enter Your Email\" />\n");
      out.write("                <button type=\"submit\">\n");
      out.write("                  Subscribe\n");
      out.write("                </button>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"info_bottom\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-2\">\n");
      out.write("            <div class=\"info_logo\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <img src=\"images/logo2.png\" alt=\"\">\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4 ml-auto\">\n");
      out.write("            <div class=\"social_box\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-facebook\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-instagram\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- end info_section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- footer section -->\n");
      out.write("  <footer class=\"footer_section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <p>\n");
      out.write("        &copy; <span id=\"displayYear\"></span> All Rights Reserved By\n");
      out.write("        <a href=\"https://html.design/\">Free Html Templates</a>\n");
      out.write("      </p>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("  <!-- footer section -->\n");
      out.write("  <script src=\"js/script.js\"></script>\n");
      out.write("  <!-- jQery -->\n");
      out.write("  <script src=\"js/jquery-3.4.1.min.js\"></script>\n");
      out.write("  <!-- popper js -->\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\">\n");
      out.write("  </script>\n");
      out.write("  <!-- bootstrap js -->\n");
      out.write("  <script src=\"js/bootstrap.js\"></script>\n");
      out.write("  <!-- owl slider -->\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\">\n");
      out.write("  </script>\n");
      out.write("  <!--  OwlCarousel 2 - Filter -->\n");
      out.write("  <script src=\"https://huynhhuynh.github.io/owlcarousel2-filter/dist/owlcarousel2-filter.min.js\"></script>\n");
      out.write("  <!-- custom js -->\n");
      out.write("  <script src=\"js/custom.js\"></script>\n");
      out.write("  <!-- Google Map -->\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap\">\n");
      out.write("  </script>\n");
      out.write("  <!-- End Google Map -->\n");
      out.write("<script>\n");
      out.write("        function autofillUsername() {\n");
      out.write("    // Get the value of the email field\n");
      out.write("    var emailInput = document.getElementById('email');\n");
      out.write("    var emailValue = emailInput.value;\n");
      out.write("\n");
      out.write("    // Extract the part before the '@' symbol\n");
      out.write("    var username = emailValue.split('@')[0];\n");
      out.write("\n");
      out.write("    // Autofill the registerUsername field\n");
      out.write("    var usernameInput = document.getElementById('empusername');\n");
      out.write("    usernameInput.value = username;\n");
      out.write("}\n");
      out.write("\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("            // Hide all sections on page load except for the initial image\n");
      out.write("            document.getElementById(\"add-employee\").style.display = \"none\";\n");
      out.write("            document.getElementById(\"show-employee\").style.display = \"none\";\n");
      out.write("            document.getElementById(\"event-history\").style.display = \"none\";\n");
      out.write("            document.getElementById(\"detailed-event\").style.display = \"none\";\n");
      out.write("        });\n");
      out.write("\n");
      out.write("function showAddEmplyee(){\n");
      out.write("    document.getElementById(\"add-employee\").style.display = \"block\";\n");
      out.write("    document.getElementById(\"show-employee\").style.display = \"none\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("function showEmplyee(){\n");
      out.write("    document.getElementById(\"add-employee\").style.display = \"none\";\n");
      out.write("    document.getElementById(\"show-employee\").style.display = \"block\";\n");
      out.write("}\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("       <div class=\"form_container\">\n");
      out.write("              <form action=\"AdminServlet?id=fetchEmp\" method=\"post\">\n");
      out.write("              <div>\n");
      out.write("                  <label for=\"username\">Username</label>\n");
      out.write("                  <input type=\"text\" id=\"username\" name=\"username\" value=\"");
      out.print(loggedInUsername);
      out.write("\" />\n");
      out.write("              </div>\n");
      out.write("              <div class=\"btn_box\">\n");
      out.write("                <button id=\"login_btn\" type=\"submit\">LOGIN</button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("<script>\n");
      out.write("                  function gotoEmployeeInfo(){\n");
      out.write("                    document.getElementById(\"login_btn\").click();\n");
      out.write("              }\n");
      out.write("              </script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("\n");
 Boolean empRegistrationSuccess = (Boolean) request.getAttribute("empRegistrationSuccess"); 
      out.write('\n');
 if (empRegistrationSuccess != null) { 
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var message = ");
      out.print( empRegistrationSuccess ? "'Employee Registration successful!'" : "'Error in registration. Please try again.'" );
      out.write(";\n");
      out.write("        alert(message);\n");
      out.write("        empRegistrationSuccess = null;\n");
      out.write("    </script>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
