/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-23 09:36:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testimonial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <!-- Basic -->\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("  <!-- Mobile Metas -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Site Metas -->\n");
      out.write("  <meta name=\"keywords\" content=\"\" />\n");
      out.write("  <meta name=\"description\" content=\"\" />\n");
      out.write("  <meta name=\"author\" content=\"\" />\n");
      out.write("\n");
      out.write("  <title>Fonicy</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- bootstrap core css -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\n");
      out.write("\n");
      out.write("  <!-- fonts style -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!--owl slider stylesheet -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" />\n");
      out.write("\n");
      out.write("  <!-- font awesome style -->\n");
      out.write("  <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- responsive style -->\n");
      out.write("  <link href=\"css/responsive.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"sub_page\">\n");
      out.write("\n");
      out.write("  <div class=\"hero_area\">\n");
      out.write("    <!-- header section strats -->\n");
      out.write("    <header class=\"header_section\">\n");
      out.write("      <div class=\"header_top\">\n");
      out.write("        <div class=\"container-fluid header_top_container\">\n");
      out.write("          <div class=\"lang_box dropdown\">\n");
      out.write("            <a href=\"#\" title=\"Language\" class=\"nav-link\" data-toggle=\"dropdown\" aria-expanded=\"true\">\n");
      out.write("              <img src=\"images/flag-uk.png\" alt=\"flag\" class=\" \" title=\"United Kingdom\"> <i class=\"fa fa-angle-down \"\n");
      out.write("                aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"dropdown-menu \">\n");
      out.write("              <a href=\"#\" class=\"dropdown-item\">\n");
      out.write("                <img src=\"images/flag-france.png\" class=\"\" alt=\"flag\">\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("            <span>\n");
      out.write("              English\n");
      out.write("            </span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"contact_nav\">\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Call : +01 123455678990\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Email : demo@gmail.com\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("              <span>\n");
      out.write("                Location\n");
      out.write("              </span>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"social_box\">\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-facebook\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"\">\n");
      out.write("              <i class=\"fa fa-instagram\" aria-hidden=\"true\"></i>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"header_bottom\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <nav class=\"navbar navbar-expand-lg custom_nav-container \">\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write("              <img src=\"images/logo.png\" alt=\"\">\n");
      out.write("            </a>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("              aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("              <span class=\"\"> </span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("              <ul class=\"navbar-nav  \">\n");
      out.write("                <li class=\"nav-item \">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"service.jsp\">Services</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"about.jsp\"> About</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"project.jsp\">Project</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item active\">\n");
      out.write("                  <a class=\"nav-link\" href=\"testimonial.jsp\">Testimonial</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"contact.jsp\">Contact Us</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"admin_login.jsp\"> Login</a>\n");
      out.write("                </li>\n");
      out.write("                <form class=\"form-inline\">\n");
      out.write("                  <button class=\"btn  my-2 my-sm-0 nav_search-btn\" type=\"submit\">\n");
      out.write("                    <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\n");
      out.write("                  </button>\n");
      out.write("                </form>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"quote_btn-container\">\n");
      out.write("                <a href=\"\" class=\"quote_btn\">\n");
      out.write("                  Get A Quote\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </nav>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- end header section -->\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- client section -->\n");
      out.write("  <section class=\"client_section layout_padding\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"heading_container heading_center\">\n");
      out.write("        <h2>\n");
      out.write("          Testimonial\n");
      out.write("        </h2>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"customCarousel2\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("      <div class=\"carousel-inner\">\n");
      out.write("        <div class=\"carousel-item active\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-10 mx-auto\">\n");
      out.write("                <div class=\"box\">\n");
      out.write("                  <div class=\"img-box\">\n");
      out.write("                    <img src=\"images/client.jpg\" alt=\"\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"detail-box\">\n");
      out.write("                    <div class=\"client_info\">\n");
      out.write("                      <div class=\"client_name\">\n");
      out.write("                        <h5>\n");
      out.write("                          Morojink\n");
      out.write("                        </h5>\n");
      out.write("                        <h6>\n");
      out.write("                          Customer\n");
      out.write("                        </h6>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p>\n");
      out.write("                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\n");
      out.write("                      labore\n");
      out.write("                      et\n");
      out.write("                      dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("                      aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n");
      out.write("                      cillum\n");
      out.write("                      dolore eu fugia\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"carousel-item\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-10 mx-auto\">\n");
      out.write("                <div class=\"box\">\n");
      out.write("                  <div class=\"img-box\">\n");
      out.write("                    <img src=\"images/client.jpg\" alt=\"\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"detail-box\">\n");
      out.write("                    <div class=\"client_info\">\n");
      out.write("                      <div class=\"client_name\">\n");
      out.write("                        <h5>\n");
      out.write("                          Morojink\n");
      out.write("                        </h5>\n");
      out.write("                        <h6>\n");
      out.write("                          Customer\n");
      out.write("                        </h6>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p>\n");
      out.write("                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\n");
      out.write("                      labore\n");
      out.write("                      et\n");
      out.write("                      dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("                      aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n");
      out.write("                      cillum\n");
      out.write("                      dolore eu fugia\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"carousel-item\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-10 mx-auto\">\n");
      out.write("                <div class=\"box\">\n");
      out.write("                  <div class=\"img-box\">\n");
      out.write("                    <img src=\"images/client.jpg\" alt=\"\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"detail-box\">\n");
      out.write("                    <div class=\"client_info\">\n");
      out.write("                      <div class=\"client_name\">\n");
      out.write("                        <h5>\n");
      out.write("                          Morojink\n");
      out.write("                        </h5>\n");
      out.write("                        <h6>\n");
      out.write("                          Customer\n");
      out.write("                        </h6>\n");
      out.write("                      </div>\n");
      out.write("                      <i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p>\n");
      out.write("                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\n");
      out.write("                      labore\n");
      out.write("                      et\n");
      out.write("                      dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("                      aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n");
      out.write("                      cillum\n");
      out.write("                      dolore eu fugia\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <ol class=\"carousel-indicators\">\n");
      out.write("        <li data-target=\"#customCarousel2\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("        <li data-target=\"#customCarousel2\" data-slide-to=\"1\"></li>\n");
      out.write("        <li data-target=\"#customCarousel2\" data-slide-to=\"2\"></li>\n");
      out.write("      </ol>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- end client section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- info section -->\n");
      out.write("  <section class=\"info_section \">\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"contact_nav\">\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Call : +01 123455678990\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Email : demo@gmail.com\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"\">\n");
      out.write("          <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("          <span>\n");
      out.write("            Location\n");
      out.write("          </span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"info_top \">\n");
      out.write("        <div class=\"row info_main_row\">\n");
      out.write("          <div class=\"col-sm-6 col-md-4 col-lg-3\">\n");
      out.write("            <div class=\"info_links\">\n");
      out.write("              <h4>\n");
      out.write("                QUICK LINKS\n");
      out.write("              </h4>\n");
      out.write("              <div class=\"info_links_menu\">\n");
      out.write("                <a class=\"\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                <a class=\"\" href=\"service.jsp\">Services</a>\n");
      out.write("                <a class=\"\" href=\"about.jsp\"> About</a>\n");
      out.write("                <a class=\"\" href=\"project.jsp\">Project</a>\n");
      out.write("                <a class=\"\" href=\"testimonial.jsp\">Testimonial</a>\n");
      out.write("                <a class=\"\" href=\"contact.jsp\">Contact Us</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-sm-6 col-md-4 col-lg-3 mx-auto\">\n");
      out.write("            <div class=\"info_post\">\n");
      out.write("              <h5>\n");
      out.write("                INSTAGRAM FEEDS\n");
      out.write("              </h5>\n");
      out.write("              <div class=\"post_box\">\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"img-box\">\n");
      out.write("                  <img src=\"images/instagram.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <div class=\"info_form\">\n");
      out.write("              <h4>\n");
      out.write("                SIGN UP TO OUR NEWSLETTER\n");
      out.write("              </h4>\n");
      out.write("              <form action=\"\">\n");
      out.write("                <input type=\"text\" placeholder=\"Enter Your Email\" />\n");
      out.write("                <button type=\"submit\">\n");
      out.write("                  Subscribe\n");
      out.write("                </button>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"info_bottom\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-2\">\n");
      out.write("            <div class=\"info_logo\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <img src=\"images/logo2.png\" alt=\"\">\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-4 ml-auto\">\n");
      out.write("            <div class=\"social_box\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-facebook\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-instagram\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- end info_section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- footer section -->\n");
      out.write("  <section class=\"footer_section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <p>\n");
      out.write("        &copy; <span id=\"displayYear\"></span> All Rights Reserved By\n");
      out.write("        <a href=\"https://html.design/\">Free Html Templates</a>\n");
      out.write("      </p>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- footer section -->\n");
      out.write("\n");
      out.write("  <!-- jQery -->\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-3.4.1.min.js\"></script>\n");
      out.write("  <!-- popper js -->\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\">\n");
      out.write("  </script>\n");
      out.write("  <!-- bootstrap js -->\n");
      out.write("  <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\n");
      out.write("  <!-- owl slider -->\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\">\n");
      out.write("  </script>\n");
      out.write("  <!--  OwlCarousel 2 - Filter -->\n");
      out.write("  <script src=\"https://huynhhuynh.github.io/owlcarousel2-filter/dist/owlcarousel2-filter.min.js\"></script>\n");
      out.write("  <!-- custom js -->\n");
      out.write("  <script type=\"text/javascript\" src=\"js/custom.js\"></script>\n");
      out.write("  <!-- Google Map -->\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap\">\n");
      out.write("  </script>\n");
      out.write("  <!-- End Google Map -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
