/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-06 12:37:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ServersidePackages.SportObject;
import java.util.Base64;
import ServersidePackages.DataObject;
import ServersidePackages.DataObject;
import java.util.List;
import com.mysql.cj.jdbc.Blob;
import java.io.*;
import java.sql.*;

public final class eventdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mysql.cj.jdbc.Blob");
    _jspx_imports_classes.add("ServersidePackages.SportObject");
    _jspx_imports_classes.add("ServersidePackages.DataObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("     <head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("      <!--=============== FAVICON ===============-->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("      <!--=============== REMIXICONS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css\" crossorigin=\"\">\n");
      out.write("      \n");
      out.write("      <!--=============== CSS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\n");
      out.write("\n");
      out.write("      <title>Event Management Website</title>\n");
      out.write("      <style>\n");
      out.write("          \n");
      out.write("          .poster-image{\n");
      out.write("              width: 580px;\n");
      out.write("              height: 85%;\n");
      out.write("              position: fixed;\n");
      out.write("              margin-left: 45%;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .all_events{\n");
      out.write("              display: flex;\n");
      out.write("              flex-wrap: wrap;\n");
      out.write("              justify-content: space-between;\n");
      out.write("          }\n");
      out.write("          \n");
      out.write("          .details_text{\n");
      out.write("              width: 50%;\n");
      out.write("              \n");
      out.write("              h1{\n");
      out.write("                  text-align: center;\n");
      out.write("              }\n");
      out.write("              \n");
      out.write("              h3{\n");
      out.write("                  text-align: right;\n");
      out.write("              }\n");
      out.write("              \n");
      out.write("              h4{\n");
      out.write("                  margin: 15px 1px;\n");
      out.write("              }\n");
      out.write("              \n");
      out.write("              p{\n");
      out.write("                  text-align: justify;\n");
      out.write("              }\n");
      out.write("          }\n");
      out.write("      </style>\n");
      out.write("   </head>\n");
      out.write("   \n");
      out.write("   <!--==================== HEADER ====================-->\n");
      out.write("      <header class=\"header\" id=\"header\">\n");
      out.write("        <nav class=\"nav container\">\n");
      out.write("            <a href=\"#\" class=\"nav__logo\">\n");
      out.write("                <img src=\"assets/img/logo.svg\" alt=\"logo\">\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"nav__menu\" id=\"nav-menu\">\n");
      out.write("                <ul class=\"nav__list\">\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav__link\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"events.jsp\" class=\"nav__link\">Events</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav__link\">About</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"contact.jsp\" class=\"nav__link\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"nav__buttons\">\n");
      out.write("                    <a href=\"login.jsp\" class=\"nav__button-ghost\">I am a Participant</a>\n");
      out.write("                    <a href=\"register.jsp\" class=\"nav__button-ghost\">I am an Organizer</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!--close button-->\n");
      out.write("                <div class=\"nav__close\" id=\"nav-close\">\n");
      out.write("                    <i class=\"ri-close-line\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--toggle button-->\n");
      out.write("            <div class=\"nav__toggle\" id=\"nav-toggle\">\n");
      out.write("                <i class=\"ri-menu-line\"></i>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("         \n");
      out.write("      </header>\n");
      out.write("   \n");
      out.write("    <body>\n");
      out.write("      <!--==================== MAIN ====================-->\n");
      out.write("      <main class=\"main\">\n");
      out.write("         <!--==================== HOME ====================-->\n");
      out.write("         <section class=\"home\">\n");
      out.write("            <div class=\"event__container container\" style=\"margin-top: 100px\">\n");
      out.write("                \n");
      out.write("<div class=\"all_events\">\n");
      out.write("    \n");
      out.write("    <div class=\"details_text\">\n");
      out.write("\n");
      out.write("    ");

        // Display event details if available in request attributes
        String e_name = (String) request.getAttribute("e_name");
        String e_type = (String) request.getAttribute("e_type");
        String e_date = (String) request.getAttribute("e_date");
        String e_time = (String) request.getAttribute("e_time");
        String e_duration = (String) request.getAttribute("e_duration");
        String e_specialattraction = (String) request.getAttribute("e_specialattraction");
        String e_description = (String) request.getAttribute("e_description");
        String e_promoter = (String) request.getAttribute("e_promoter");
        String e_venue = (String) request.getAttribute("e_venue");
        String e_addline1 = (String) request.getAttribute("e_addline1");
        String e_addline2 = (String) request.getAttribute("e_addline2");
        String e_city = (String) request.getAttribute("e_city");
        String e_state = (String) request.getAttribute("e_state");
        String e_post = (String) request.getAttribute("e_post");
        String e_country = (String) request.getAttribute("e_country");
        int e_tickets = (int) request.getAttribute("e_tickets");
        String e_contactpersonfirst = (String) request.getAttribute("e_contactpersonfirst");
        String e_conatactpersonlast = (String) request.getAttribute("e_conatactpersonlast");
        String e_contactemail = (String) request.getAttribute("e_contactemail");
        String e_contactnumber = (String) request.getAttribute("e_contactnumber");
        String e_isrecord = (String) request.getAttribute("e_isrecord");
        String e_organizer = (String) request.getAttribute("e_organizer");

        if (e_name != null && e_date != null) {
    
      out.write("\n");
      out.write("            <h1>");
      out.print( e_name );
      out.write("</h1>\n");
      out.write("            <h4>Category: ");
      out.print( e_type );
      out.write("</h4>\n");
      out.write("            <h3>Date & Time: ");
      out.print( e_date );
      out.write(" at ");
      out.print( e_time );
      out.write("</h3>\n");
      out.write("            <h3>Duration: ");
      out.print( e_duration );
      out.write("</h3>\n");
      out.write("            <h4>Special Attraction: ");
      out.print( e_specialattraction );
      out.write("</h4>\n");
      out.write("            <p><b>Description:</b> ");
      out.print( e_description );
      out.write("</p>\n");
      out.write("            <h4>Promoter: ");
      out.print( e_promoter );
      out.write("</h4>\n");
      out.write("            <h4>Venue Name: ");
      out.print( e_venue );
      out.write("</h4>\n");
      out.write("            <p><b>Venue address:</b> ");
      out.print( e_addline1 );
      out.write(',');
      out.write(' ');
      out.print( e_addline2 );
      out.write(',');
      out.write(' ');
      out.print( e_city );
      out.write(',');
      out.write(' ');
      out.print( e_state );
      out.write(',');
      out.write(' ');
      out.print( e_country );
      out.write(',');
      out.write(' ');
      out.print( e_post );
      out.write("</p>\n");
      out.write("            <h4>Entry fees: ");
      out.print( e_tickets );
      out.write("</h4>\n");
      out.write("            <h4>Contact Person: ");
      out.print( e_contactpersonfirst );
      out.write(' ');
      out.print( e_conatactpersonlast );
      out.write("</h4>\n");
      out.write("            <h4>Email ID: ");
      out.print( e_contactemail );
      out.write("</h4>\n");
      out.write("            <h4>Mobile Number: ");
      out.print( e_contactnumber );
      out.write("</h4>\n");
      out.write("            <h5>Will event be recorded?: ");
      out.print( e_isrecord );
      out.write("</h5>\n");
      out.write("            <p style=\"display: none\">Organizer: ");
      out.print( e_organizer );
      out.write("</p>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("            ");
 Blob e_poster = (Blob) request.getAttribute("e_poster");
       if (e_poster != null) {
           byte[] imageBytes = e_poster.getBytes(1, (int) e_poster.length());
           String base64Image = javax.xml.bind.DatatypeConverter.printBase64Binary(imageBytes);
    
      out.write("\n");
      out.write("           <img src=\"data:image/jpeg;base64, ");
      out.print(base64Image);
      out.write(" \" alt=\"Event Poster\" class=\"poster-image\">   \n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                \n");
      out.write("<!--                <div class=\"home__images\">\n");
      out.write("                    <img src=\"assets/img/img-44.png\" alt=\"image\" class=\"home__img-4\"  style=\"z-index: -1; filter: blur(3px); position: fixed;\">\n");
      out.write("                    <img src=\"assets/img/img-3.png\" alt=\"image\" class=\"home__img-3\"  style=\"z-index: -1; filter: blur(3px); position: fixed;\">\n");
      out.write("                    <img src=\"assets/img/img-2.png\" alt=\"image\" class=\"home__img-2\"  style=\"z-index: -1; filter: blur(3px); position: fixed;\">\n");
      out.write("                    <img src=\"assets/img/img-11.png\" alt=\"image\" class=\"home__img-1\"  style=\"z-index: -1; filter: blur(3px); position: fixed;\">\n");
      out.write("                </div>-->\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("         </section>\n");
      out.write("      </main>\n");
      out.write("      \n");
      out.write("     \n");
      out.write("   </body>\n");
      out.write("   \n");
      out.write("<script src=\"assets/js/gsap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MAIN JS -->\n");
      out.write("<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"script.js\"></script>\n");
      out.write("   \n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
