/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 08:43:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class organizer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1708593945501L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1709279224139L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("   <head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("      <!--=============== FAVICON ===============-->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("      <!--=============== REMIXICONS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css\" crossorigin=\"\">\n");
      out.write("      \n");
      out.write("      <!--=============== CSS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\n");
      out.write("\n");
      out.write("      <title>Event Management Website</title>\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("   <!--==================== HEADER ====================-->\n");
      out.write("      <header class=\"header\" id=\"header\">\n");
      out.write("        <nav class=\"nav container\">\n");
      out.write("            <a href=\"#\" class=\"nav__logo\">\n");
      out.write("                <img src=\"assets/img/logo.svg\" alt=\"logo\">\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"nav__menu\" id=\"nav-menu\">\n");
      out.write("                <ul class=\"nav__list\">\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav__link\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"#\" class=\"nav__link\">Pricing</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"#\" class=\"nav__link\">Events</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"#\" class=\"nav__link\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"nav__buttons\">\n");
      out.write("                    <a href=\"login.jsp\" class=\"nav__button-link\">Login</a>\n");
      out.write("                    <a href=\"register.jsp\" class=\"nav__button-ghost\">Register as a Organizer</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!--close button-->\n");
      out.write("                <div class=\"nav__close\" id=\"nav-close\">\n");
      out.write("                    <i class=\"ri-close-line\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--toggle button-->\n");
      out.write("            <div class=\"nav__toggle\" id=\"nav-toggle\">\n");
      out.write("                <i class=\"ri-menu-line\"></i>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("         \n");
      out.write("      </header>\n");
      out.write("   \n");
      out.write("   </body>");
      out.write('\n');
 String loggedInUsername = (String) request.getAttribute("loggedInUsername"); 
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Event Organizer Dashboard</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/organizerpage.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/post_event_form.css\">\n");
      out.write("    <script src=\"assets/js/script.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"org-container\">\n");
      out.write("    <script src=\"script.js\"></script>\n");
      out.write("    \n");
      out.write("    <div class=\"org__images\">\n");
      out.write("                    <img src=\"assets/img/img-3000.jpg\" alt=\"image\" class=\"org__img-4\">\n");
      out.write("                    <img src=\"assets/img/img-3.png\" alt=\"image\" class=\"home__img-3\">\n");
      out.write("                    <img src=\"assets/img/img-2.png\" alt=\"image\" class=\"home__img-2\">\n");
      out.write("                    <img src=\"assets/img/img-11.png\" alt=\"image\" class=\"home__img-1\">\n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        <h2>Welcome, ");
      out.print( loggedInUsername );
      out.write("!</h2><br>\n");
      out.write("        <!-- Left Sidebar with options -->\n");
      out.write("        <a href=\"#\" onclick=\"showOrganizerProfile()\">Organizer Profile</a>\n");
      out.write("        <a href=\"#\" onclick=\"showEventForm()\">Post an Event</a>\n");
      out.write("        <a href=\"#\" onclick=\"showEventHistory()\">Event History</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <!-- Initial Image Section -->\n");
      out.write("        <section id=\"initial-image\">\n");
      out.write("            \n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Organizer Profile Section -->\n");
      out.write("        <section id=\"organizer-profile\" style=\"display: none;\">\n");
      out.write("            <h2>organizer profile</h2>\n");
      out.write("            ");

        // Display organizer details if available in request attributes
        String organizerName = (String) request.getAttribute("organizerName");
        String organizerOrg = (String) request.getAttribute("organizerOrg");
        String organizerEmail = (String) request.getAttribute("organizerEmail");
        String organizerMobile = (String) request.getAttribute("organizerMobile");

        if (organizerName != null && organizerEmail != null) {
    
      out.write("\n");
      out.write("            <p>Name: ");
      out.print( organizerName );
      out.write("</p>\n");
      out.write("            <p>Organization: ");
      out.print( organizerOrg );
      out.write("</p>\n");
      out.write("            <p>Email: ");
      out.print( organizerEmail );
      out.write("</p>\n");
      out.write("            <p>Mobile No: ");
      out.print( organizerMobile );
      out.write("</p>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Post an Event Section -->\n");
      out.write("        <section id=\"event-form\" style=\"display: none;\">\n");
      out.write("            \n");
      out.write("      <div class=\"testbox\">\n");
      out.write("      <form action=\"Servlet?id=postevent\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("          <div class=\"banner\" >\n");
      out.write("              <img src=\"assets/img/post_event_form.jpg\" class=\"banner_img\">\n");
      out.write("          <h1>Event Posting Form</h1>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Name of Event</p>\n");
      out.write("          <input type=\"text\" name=\"eventname\" />\n");
      out.write("        </div>\n");
      out.write("          <div class=\"item\">\n");
      out.write("          <p>Type of Event</p>\n");
      out.write("          <select name=\"event_type\">\n");
      out.write("            <option value=\"\"></option>\n");
      out.write("            <option value=\"Please select\" selected>*Please select from below options*</option>\n");
      out.write("            <option value=\"Sports\">Sports</option>\n");
      out.write("            <option value=\"Trekking / Adventures\">Trekking / Adventures</option>\n");
      out.write("            <option value=\"Cultural\">Cultural</option>\n");
      out.write("            <option value=\"Musical / DJ\">Musical / DJ</option>\n");
      out.write("            <option value=\"Business\">Business</option>\n");
      out.write("            <option value=\"Educational\">Educational</option>\n");
      out.write("            <option value=\"Promos\">Promos</option>\n");
      out.write("            <option value=\"Expos\">Expos</option>\n");
      out.write("          </select>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Date of Event</p>\n");
      out.write("          <input type=\"text\" name=\"bdate\" placeholder=\"dd-mm-yyyy\"/>\n");
      out.write("          <i class=\"fas fa-calendar-alt\"></i>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Time of Event</p>\n");
      out.write("          <input type=\"text\" name=\"event_time\" />\n");
      out.write("          <i class=\"fas fa-clock\"></i>\n");
      out.write("        </div>\n");
      out.write("          <div class=\"item\">\n");
      out.write("          <p>Set Duration</p>\n");
      out.write("          <input type=\"text\" name=\"duration\"/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Special Attraction</p>\n");
      out.write("          <input type=\"text\" name=\"specialAttraction\"/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Description of Event</p>\n");
      out.write("          <textarea rows=\"3\" name=\"description\"></textarea>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Organizer's Name</p>\n");
      out.write("          <input type=\"text\" name=\"promoter\"/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Venue Name</p>\n");
      out.write("          <input type=\"text\" name=\"venue_name\"/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Venue Address</p>\n");
      out.write("          <input type=\"text\" name=\"add1\" placeholder=\"Street address\" />\n");
      out.write("          <input type=\"text\" name=\"add2\" placeholder=\"Street address line 2\" />\n");
      out.write("          <div class=\"city-item\">\n");
      out.write("            <input type=\"text\" name=\"city\" placeholder=\"City\" />\n");
      out.write("            <input type=\"text\" name=\"state\" placeholder=\"State/Region\" />\n");
      out.write("            <input type=\"text\" name=\"pin\" placeholder=\"Postal / Zip code\" />\n");
      out.write("            <input type=\"text\" name=\"country\" placeholder=\"Country\" />\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Available Tickets</p>\n");
      out.write("          <input type=\"text\" name=\"ticket_count\"/>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Contact Person</p>\n");
      out.write("          <div class=\"name-item\">\n");
      out.write("            <input type=\"text\" name=\"firstname\" placeholder=\"First\" />\n");
      out.write("            <input type=\"text\" name=\"lastname\" placeholder=\"Last\" />\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Contact Email</p>\n");
      out.write("          <input type=\"text\" name=\"email\"/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item\">\n");
      out.write("          <p>Contact Number</p>\n");
      out.write("          <input type=\"text\" name=\"con_num\"/>\n");
      out.write("        </div>\n");
      out.write("          <div>\n");
      out.write("           <label for=\"poster\">Upload Event Poster</label>\n");
      out.write("           <input type=\"file\" id=\"poster\" name=\"poster\" accept=\"image/*\" />\n");
      out.write("         </div>\n");
      out.write("        <div class=\"question\">\n");
      out.write("          <p>Will this event be recorded?</p>\n");
      out.write("          <div class=\"question-answer\">\n");
      out.write("            <div>\n");
      out.write("              <input type=\"radio\" value=\"Yes\" id=\"radio_1\" name=\"recorded\" />\n");
      out.write("              <label for=\"radio_1\" class=\"radio\"><span>Yes</span></label>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("              <input type=\"radio\" value=\"No\" id=\"radio_2\" name=\"recorded\" />\n");
      out.write("              <label for=\"radio_2\" class=\"radio\"><span>No</span></label>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"btn-block\">\n");
      out.write("          <button type=\"submit\">POST EVENT</button>\n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("            \n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Event History Section -->\n");
      out.write("        <section id=\"event-history\" style=\"display: none;\">\n");
      out.write("            <h2>Event History</h2>\n");
      out.write("            <!-- Overview of posted events goes here -->\n");
      out.write("            <!-- Display poster image, event name, date, etc. -->\n");
      out.write("            <div class=\"event-overview\" onclick=\"showDetailedEvent(1)\">\n");
      out.write("                <!-- Event Overview Content -->\n");
      out.write("                <img src=\"event_poster.jpg\" alt=\"Event Poster\">\n");
      out.write("                <p>Event Name</p>\n");
      out.write("                <p>Date of Event</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Add more event overviews as needed -->\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Detailed Event Information Section -->\n");
      out.write("        <section id=\"detailed-event\" style=\"display: none;\">\n");
      out.write("            <!-- Detailed event information goes here -->\n");
      out.write("            <h2>Event Details</h2>\n");
      out.write("            <!-- Display detailed information for the selected event -->\n");
      out.write("            <!-- Include all the details mentioned in the question -->\n");
      out.write("            <p>Detailed information for the selected event goes here.</p>\n");
      out.write("        </section>\n");
      out.write("    </div>  \n");
      out.write("</body>\n");
      out.write("\n");
 Boolean loginSuccess = (Boolean) request.getAttribute("loginSuccess"); 
      out.write('\n');
 Boolean eventPostSuccess = (Boolean) request.getAttribute("eventPostSuccess"); 
      out.write('\n');
 if (loginSuccess != null) { 
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var message = ");
      out.print( loginSuccess ? "'Login successful!'" : "'Error in login. Please try again.'" );
      out.write(";\n");
      out.write("        alert(message);\n");
      out.write("    </script>\n");
 } 
      out.write('\n');
      out.write('\n');
 if (eventPostSuccess != null) { 
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var message = ");
      out.print( eventPostSuccess ? "'Event posted successfully!'" : "'Error in posting. Please try again.'" );
      out.write(";\n");
      out.write("        alert(message);\n");
      out.write("    </script>\n");
 } 
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("<!-- footer.jsp -->\n");
      out.write("<!-- GSAP -->\n");
      out.write("<script src=\"assets/js/gsap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MAIN JS -->\n");
      out.write("<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"script.js\"></script>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
