/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-26 04:44:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Base64;
import ServersidePackages.DataObject;
import ServersidePackages.DataObject;
import java.util.List;
import com.mysql.cj.jdbc.Blob;
import java.io.*;
import java.sql.*;

public final class vieweventdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mysql.cj.jdbc.Blob");
    _jspx_imports_classes.add("ServersidePackages.DataObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 String loggedInUsername = (String) request.getAttribute("loggedInParticipant"); 
      out.write('\n');
 String status = (String) request.getAttribute("status"); 
      out.write('\n');
 int eventID = (Integer)request.getAttribute("event-id"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("     <head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("      <!--=============== FAVICON ===============-->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("      <!--=============== REMIXICONS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css\" crossorigin=\"\">\n");
      out.write("      \n");
      out.write("      <!--=============== CSS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/organizerpage.css\">\n");
      out.write("\n");
      out.write("      <title>Event Organizer Dashboard</title>\n");
      out.write("      <style>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background: linear-gradient(to right bottom, #ffffff, #02effe);\n");
      out.write("            color: #fff;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .view_container {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 80px auto auto auto;\n");
      out.write("            padding: 50px;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .text-section {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            color: #fff;\n");
      out.write("            height: 700px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 50px;\n");
      out.write("            overflow-y: scroll;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .view-button{\n");
      out.write("                background-color: #a82877;\n");
      out.write("                color: #fff;\n");
      out.write("                padding-top: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                padding-bottom: 9px;\n");
      out.write("                padding-left: 15px;\n");
      out.write("                padding-right: 15px;\n");
      out.write("                margin-left: 5px;\n");
      out.write("                margin-top: 5px;\n");
      out.write("            }\n");
      out.write("            .view-button:hover{\n");
      out.write("                background-color: black;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .btn-block button {\n");
      out.write("            background-color: #a82877;\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            width: 170px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .btn-block button:hover {\n");
      out.write("            background-color: black;\n");
      out.write("        }\n");
      out.write("        .image-section {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            padding: 20px;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 700px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .postevent{\n");
      out.write("                margin-top: 20px;\n");
      out.write("                box-shadow: 0 0 0px 0 #ffffff;\n");
      out.write("            }\n");
      out.write("h1 {\n");
      out.write("    font-size: 2.5rem;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    color: #333; /* Dark color for headings */\n");
      out.write("}\n");
      out.write("\n");
      out.write("h4 {\n");
      out.write("    font-size: 1.2rem;\n");
      out.write("    margin-bottom: 5px;\n");
      out.write("    color: #555; /* Slightly darker color for subheadings */\n");
      out.write("}\n");
      out.write("\n");
      out.write("h3 {\n");
      out.write("    font-size: 1.3rem;\n");
      out.write("    margin-bottom: 5px;\n");
      out.write("    color: #666; /* Another shade for headings */\n");
      out.write("}\n");
      out.write("\n");
      out.write("p {\n");
      out.write("    font-size: 1.1rem;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    text-align: justify;\n");
      out.write("}\n");
      out.write("\n");
      out.write("b {\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: #222; /* Darker color for emphasis */\n");
      out.write("}\n");
      out.write("\n");
      out.write("h5 {\n");
      out.write("    font-size: 1rem;\n");
      out.write("    margin-top: 10px;\n");
      out.write("    margin-bottom: 5px;\n");
      out.write("    color: #888; /* Light color for secondary information */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Advanced Styling */\n");
      out.write("h1, h3, h4, h5, p {\n");
      out.write("    transition: all 0.3s ease-in-out; /* Smooth transition for hover effects */\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1:hover, h3:hover, h4:hover, h5:hover, p:hover {\n");
      out.write("    color: #e76eb9; /* Change color on hover */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Gradient Background for Headers */\n");
      out.write("h1, h3, h4, h5 {\n");
      out.write("    background: linear-gradient(45deg, #adfaff, #fefefe); /* Gradient background */\n");
      out.write("    -webkit-background-clip: text; /* Clip text to the background */\n");
      out.write("    -webkit-text-fill-color: transparent; /* Transparent text to show the gradient */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Box Shadow for Text Content */\n");
      out.write("h1, h3, h4, h5, p {\n");
      out.write("    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Soft shadow */\n");
      out.write("    padding: 10px; /* Add padding to give depth */\n");
      out.write("    border-radius: 8px; /* Rounded corners */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Special Attraction Highlight */\n");
      out.write("h4:nth-of-type(3) {\n");
      out.write("    color: #a82877; /* Highlight color for special attraction */\n");
      out.write("}\n");
      out.write("\n");
      out.write("        .image-section img {\n");
      out.write("            max-width: 100%;\n");
      out.write("            max-height: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            /* For smaller screens, switch to a single column layout */\n");
      out.write("            .container {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("                height: auto;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .text-section, .image-section {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("   </head>\n");
      out.write("   \n");
      out.write("   <!--==================== HEADER ====================-->\n");
      out.write("      <header class=\"header\" id=\"header\">\n");
      out.write("        <nav class=\"nav container\">\n");
      out.write("            <a href=\"#\" class=\"nav__logo\">\n");
      out.write("                <img src=\"assets/img/logo.svg\" alt=\"logo\">\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"nav__menu\" id=\"nav-menu\">\n");
      out.write("                <ul class=\"nav__list\">\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav__link\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"#\" class=\"nav__link\">Events</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav__link\">About</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"contact.jsp\" class=\"nav__link\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"nav__buttons\">\n");
      out.write("                    <!--<a href=\"#\" class=\"nav__button-link\" onclick=\"openEditEvent()\">");
      out.print( loggedInUsername );
      out.write("</a>-->\n");
      out.write("                    <form class=\"postevent\" action=\"ParticipantServlet?id=loadParticipant\" method=\"post\">\n");
      out.write("    <input type=\"hidden\" name=\"username\" value=\"");
      out.print( loggedInUsername );
      out.write("\">\n");
      out.write("    <button type=\"submit\" class=\"nav__button-ghost\">");
      out.print( loggedInUsername );
      out.write("</button>\n");
      out.write("</form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!--close button-->\n");
      out.write("                <div class=\"nav__close\" id=\"nav-close\">\n");
      out.write("                    <i class=\"ri-close-line\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--toggle button-->\n");
      out.write("            <div class=\"nav__toggle\" id=\"nav-toggle\">\n");
      out.write("                <i class=\"ri-menu-line\"></i>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("         \n");
      out.write("      </header>\n");
      out.write("    \n");
      out.write("   <div class=\"view_container\">\n");
      out.write("       ");

        // Display event details if available in request attributes
        String e_name = (String) request.getAttribute("e_name");
        String e_type = (String) request.getAttribute("e_type");
        String e_date = (String) request.getAttribute("e_date");
        String e_time = (String) request.getAttribute("e_time");
        String e_duration = (String) request.getAttribute("e_duration");
        String e_specialattraction = (String) request.getAttribute("e_specialattraction");
        String e_description = (String) request.getAttribute("e_description");
        String e_promoter = (String) request.getAttribute("e_promoter");
        String e_venue = (String) request.getAttribute("e_venue");
        String e_addline1 = (String) request.getAttribute("e_addline1");
        String e_addline2 = (String) request.getAttribute("e_addline2");
        String e_city = (String) request.getAttribute("e_city");
        String e_state = (String) request.getAttribute("e_state");
        String e_post = (String) request.getAttribute("e_post");
        String e_country = (String) request.getAttribute("e_country");
        String e_tickets = (String) request.getAttribute("e_tickets");
        String e_contactpersonfirst = (String) request.getAttribute("e_contactpersonfirst");
        String e_conatactpersonlast = (String) request.getAttribute("e_conatactpersonlast");
        String e_contactemail = (String) request.getAttribute("e_contactemail");
        String e_contactnumber = (String) request.getAttribute("e_contactnumber");
        String e_isrecord = (String) request.getAttribute("e_isrecord");
        String e_organizer = (String) request.getAttribute("e_organizer");

        if (e_name != null && e_date != null) {
    
      out.write("\n");
      out.write("   \n");
      out.write("        <div id=\"text-section\" class=\"text-section\">\n");
      out.write("            \n");
      out.write("         \n");
      out.write("            <h2 id=\"status\">");
      out.print( status );
      out.write("</h2>\n");
      out.write("            <h2>");
      out.print( e_name );
      out.write("</h2>\n");
      out.write("    \n");
      out.write("            <h4>Category: ");
      out.print( e_type );
      out.write("</h4>\n");
      out.write("            <h3>Date & Time: ");
      out.print( e_date );
      out.write(" at ");
      out.print( e_time );
      out.write("</h3>\n");
      out.write("            <h3>Duration: ");
      out.print( e_duration );
      out.write("</h3>\n");
      out.write("            <h4>Special Attraction: ");
      out.print( e_specialattraction );
      out.write("</h4>\n");
      out.write("            <p><b>Description:</b> ");
      out.print( e_description );
      out.write("</p>\n");
      out.write("            <h4>Organizer's Name: ");
      out.print( e_promoter );
      out.write("</h4>\n");
      out.write("            <h4>Venue Name: ");
      out.print( e_venue );
      out.write("</h4>\n");
      out.write("            <p><b>Venue address:</b> ");
      out.print( e_addline1 );
      out.write(',');
      out.write(' ');
      out.print( e_addline2 );
      out.write(',');
      out.write(' ');
      out.print( e_city );
      out.write(',');
      out.write(' ');
      out.print( e_state );
      out.write(',');
      out.write(' ');
      out.print( e_country );
      out.write(',');
      out.write(' ');
      out.print( e_post );
      out.write("</p>\n");
      out.write("            <h4>Entry fees: ");
      out.print( e_tickets );
      out.write("</h4>\n");
      out.write("            <h4>Contact Person: ");
      out.print( e_contactpersonfirst );
      out.write(' ');
      out.print( e_conatactpersonlast );
      out.write("</h4>\n");
      out.write("            <h4>Email ID: ");
      out.print( e_contactemail );
      out.write("</h4>\n");
      out.write("            <h4>Mobile Number: ");
      out.print( e_contactnumber );
      out.write("</h4>\n");
      out.write("            <h5>Will event be recorded?: ");
      out.print( e_isrecord );
      out.write("</h5>\n");
      out.write("            <form action=\"ParticipantServlet?id=register_for_event\" method=\"post\" style=\"display: none;\">\n");
      out.write("                <input type=\"hidden\" name=\"e_id\" value=\"");
      out.print( eventID );
      out.write("\"/>\n");
      out.write("                <input type=\"hidden\" name=\"org_username\" value=\"");
      out.print( e_organizer );
      out.write("\"/>\n");
      out.write("                <input type=\"hidden\" name=\"p_username\" value=\"");
      out.print( loggedInUsername );
      out.write("\"/>\n");
      out.write("                <input type=\"hidden\" name=\"reg_id\" value=\"");
      out.print( eventID );
      out.write('_');
      out.write('_');
      out.print( loggedInUsername );
      out.write("\"/>\n");
      out.write("                <button id=\"reg_btn\" type=\"submit\"></button>\n");
      out.write("            </form><br><br>\n");
      out.write("            <form action=\"ParticipantServlet?id=cancelReg\" method=\"post\" style=\"display: none;\">\n");
      out.write("                <input type=\"hidden\" name=\"e_id\" value=\"");
      out.print( eventID );
      out.write("\"/>\n");
      out.write("                <input type=\"hidden\" name=\"p_username\" value=\"");
      out.print( loggedInUsername );
      out.write("\"/>\n");
      out.write("                <input type=\"hidden\" name=\"reg_id\" value=\"");
      out.print( eventID );
      out.write('_');
      out.write('_');
      out.print( loggedInUsername );
      out.write("\"/>\n");
      out.write("                <button id=\"cancelRegbtn\" type=\"submit\"></button>\n");
      out.write("            </form><br><br>\n");
      out.write("            <div id=\"regbtn\">\n");
      out.write("                <a href=\"#\" class=\"view-button\" onclick=\"regForEvent()\">Register for the event</a>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"cancel_regbtn\" style=\"display: none;\">\n");
      out.write("                <a href=\"#\" class=\"view-button\" onclick=\"cancelReg()\">Cancel Registration</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("            \n");
      out.write("        <div id=\"image-section\" class=\"image-section\">\n");
      out.write("                            ");
 Blob e_poster = (Blob) request.getAttribute("e_poster");
       if (e_poster != null) {
           byte[] imageBytes = e_poster.getBytes(1, (int) e_poster.length());
           String base64Image = javax.xml.bind.DatatypeConverter.printBase64Binary(imageBytes);
    
      out.write("\n");
      out.write("           <img src=\"data:image/jpeg;base64, ");
      out.print(base64Image);
      out.write(" \" alt=\"Event Poster\" class=\"poster-image\">   \n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("          ");

        }
    
      out.write("     \n");
      out.write("            \n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    window.onload = function(){\n");
      out.write("        hideRegBtn();\n");
      out.write("    };\n");
      out.write("    function regForEvent(){\n");
      out.write("        document.getElementById(\"reg_btn\").click();\n");
      out.write("    }\n");
      out.write("    function cancelReg(){\n");
      out.write("        document.getElementById(\"cancelRegbtn\").click();\n");
      out.write("    }\n");
      out.write("    function hideRegBtn(){\n");
      out.write("    var st = document.getElementById(\"status\").textContent;\n");
      out.write("    if (st === \"Registered\") {\n");
      out.write("        document.getElementById(\"regbtn\").style.display = \"none\";\n");
      out.write("        document.getElementById(\"cancel_regbtn\").style.display = \"block\";\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("   \n");
      out.write("<script src=\"assets/js/gsap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MAIN JS -->\n");
      out.write("<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"assets/js/script.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
