/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-19 10:51:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Base64;
import ServersidePackages.ProjectObject;
import ServersidePackages.ClientObject;
import java.util.List;
import com.mysql.cj.jdbc.Blob;
import java.io.*;
import java.sql.*;

public final class managerdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ServersidePackages.ProjectObject");
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mysql.cj.jdbc.Blob");
    _jspx_imports_classes.add("ServersidePackages.ClientObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 String managerUsername = (String) request.getAttribute("manager_username"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("     <head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("      <!--=============== FAVICON ===============-->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("      <!--=============== REMIXICONS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css\" crossorigin=\"\">\n");
      out.write("      \n");
      out.write("      <!--=============== CSS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/organizerpage.css\">\n");
      out.write("\n");
      out.write("      <title>Manager Dashboard</title>\n");
      out.write("      <style>\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background: linear-gradient(to right bottom, #ffffff, #02effe);\n");
      out.write("            color: #fff;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .poster-image {\n");
      out.write("            width: 200px; /* Adjust width as needed */\n");
      out.write("            height: 250px; /* Auto adjust height to maintain aspect ratio */\n");
      out.write("        }\n");
      out.write("        .org_container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 100px auto;\n");
      out.write("            padding: 20px;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("        .section {\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        h2 {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 20px;\n");
      out.write("            background: linear-gradient(to right bottom, #319da4c9, #3231a4);\n");
      out.write("            text-align: center;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 24px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .heading{\n");
      out.write("            height: min-content;\n");
      out.write("        }\n");
      out.write("        .action_btn{\n");
      out.write("            height: min-content;\n");
      out.write("            cursor: pointer;\n");
      out.write("            display: flex;\n");
      out.write("            \n");
      out.write("            h2{\n");
      out.write("                    background: linear-gradient(to right bottom, #45f0fbc9, #3231a4);\n");
      out.write("                    margin: auto;\n");
      out.write("                    width: 48%;\n");
      out.write("                    border-radius: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h2:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h3{\n");
      out.write("                    background: linear-gradient(to right bottom, #45f0fbc9, #3231a4);\n");
      out.write("                    margin: auto;\n");
      out.write("                    text-align: center;\n");
      out.write("                    font-weight: bold;\n");
      out.write("                    font-size: 24px;\n");
      out.write("                    padding: 20px;\n");
      out.write("                    border-radius: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h3:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("            \n");
      out.write("            form{\n");
      out.write("                /*box-shadow: 0 0 0px 0 #ffffff;*/\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        /* Profile Section */\n");
      out.write("        .profile {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 40px;\n");
      out.write("            height: 730px;\n");
      out.write("            \n");
      out.write("            h2{\n");
      out.write("                background: linear-gradient(to right bottom, #319da4c9, #3231a4);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        .profile p {\n");
      out.write("            margin: 10px 0;\n");
      out.write("            font-size: 18px;\n");
      out.write("        }\n");
      out.write("        .profile button {\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .profile button:hover {\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .edit{\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("            .cancel-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                padding-top: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                padding-bottom: 7px;\n");
      out.write("                padding-left: 15px;\n");
      out.write("                padding-right: 15px;\n");
      out.write("                margin-left: 5px;\n");
      out.write("            }\n");
      out.write("            .cancel-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            .back-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                margin-left: 420px;\n");
      out.write("                width: 100px;\n");
      out.write("                height: 25px;\n");
      out.write("                position: fixed;\n");
      out.write("                margin-top: 650px;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .back-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            .logout-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                padding-top: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                padding-bottom: 7px;\n");
      out.write("                padding-left: 15px;\n");
      out.write("                padding-right: 15px;\n");
      out.write("                margin-left: 5px;\n");
      out.write("                margin-top: 10px;\n");
      out.write("            }\n");
      out.write("            .logout-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("\n");
      out.write("        /* Events Section */\n");
      out.write("        .events {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            padding: 20px;\n");
      out.write("            height: 730px;\n");
      out.write("            overflow-y: scroll;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("        }\n");
      out.write("        .event {\n");
      out.write("            background: linear-gradient(to right bottom, hsl(258.09deg 76.62% 70.36%), #dcacacba);\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("            cursor: pointer;\n");
      out.write("            position: relative;\n");
      out.write("            height: 290px;\n");
      out.write("            column-gap: 20px;\n");
      out.write("            display: flex;\n");
      out.write("        }\n");
      out.write("        .event:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("        }\n");
      out.write("        .event h3 {\n");
      out.write("            margin: 0 0 10px;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("        .event p {\n");
      out.write("            margin: 5px 0;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        .event-info {\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\n");
      out.write("        }\n");
      out.write("        .msg-details{\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 40px 10px 10px 10px;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        .event-actions {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 10px;\n");
      out.write("            right: 10px;\n");
      out.write("            opacity: 0;\n");
      out.write("            transition: opacity 0.3s;\n");
      out.write("        }\n");
      out.write("        .event:hover .event-actions {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("        .event-actions button {\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 5px 10px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin: 5px 5px;\n");
      out.write("            width: 150px;\n");
      out.write("        }\n");
      out.write("        .event-actions button:hover {\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .event_form{\n");
      out.write("            margin: 10px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .post-button{\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("        }\n");
      out.write("        .post-button:hover{\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .msg-desc{\n");
      out.write("            height: 200px;\n");
      out.write("            overflow-y: scroll;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("            text-align: justify;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .msg_info{\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("   </head>\n");
      out.write("   \n");
      out.write("   <!--==================== HEADER ====================-->\n");
      out.write("      <header class=\"header\" id=\"header\">\n");
      out.write("        <nav class=\"nav container\">\n");
      out.write("            <a href=\"#\" class=\"nav__logo\">\n");
      out.write("                <img src=\"assets/img/logo.png\" alt=\"logo\">\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"nav__menu\" id=\"nav-menu\">\n");
      out.write("                <ul class=\"nav__list\">\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav__link\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav__link\">About</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"contact.jsp\" class=\"nav__link\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("                <!--close button-->\n");
      out.write("                <div class=\"nav__close\" id=\"nav-close\">\n");
      out.write("                    <i class=\"ri-close-line\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--toggle button-->\n");
      out.write("            <div class=\"nav__toggle\" id=\"nav-toggle\">\n");
      out.write("                <i class=\"ri-menu-line\"></i>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("         \n");
      out.write("      </header>\n");
      out.write("    \n");
      out.write("   <div class=\"org_container\">\n");
      out.write("        <!-- Profile Section -->\n");
      out.write("        <div id=\"profile\" class=\"section profile\">\n");
      out.write("            <h3>Hello, ");
      out.print( managerUsername );
      out.write("!</h3><br>\n");
      out.write("            <h3>Welcome to Project Manager Dashboard!</h3><br>\n");
      out.write("            ");

        // Display organizer details if available in request attributes
        int id = (Integer) request.getAttribute("id");
        String name = (String) request.getAttribute("name");
        String dob = (String) request.getAttribute("dob");
        String email = (String) request.getAttribute("email");
        String mobile = (String) request.getAttribute("mobile");
        String idtype = (String) request.getAttribute("idtype");
        String idnum = (String) request.getAttribute("idnumber");
        String desig = (String) request.getAttribute("designation");
        String salary = (String) request.getAttribute("salary");
        String cur_add = (String) request.getAttribute("current_address");
        String per_add = (String) request.getAttribute("permenant_address");

        if (name != null && email != null) {
    
      out.write("\n");
      out.write("            \n");
      out.write("            <p><strong>Id:</strong> ");
      out.print( id);
      out.write("</p>\n");
      out.write("            <p><strong>Name:</strong> ");
      out.print( name);
      out.write("</p>\n");
      out.write("            ");

        }
    
      out.write("\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewManagerProfile()\">View Full Profile</a>\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewChangePassForm()\">Change Password</a>\n");
      out.write("    <a href=\"index.jsp\" class=\"logout-button\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("            <div id=\"view_manager_profile\" class=\"section profile edit\" style=\"align-items: baseline;\">\n");
      out.write("                <h2 style=\"margin: auto\">Project Manager Profile</h2>\n");
      out.write("                <p><strong>Id:</strong> ");
      out.print( id);
      out.write("</p>\n");
      out.write("                <p><strong>Name:</strong> ");
      out.print( name);
      out.write("</p>\n");
      out.write("                <p><strong>Date of Birth:</strong> ");
      out.print( dob);
      out.write("</p>\n");
      out.write("                <p><strong>Email Id:</strong> ");
      out.print( email);
      out.write("</p>\n");
      out.write("                <p><strong>Mobile Number:</strong> ");
      out.print( mobile);
      out.write("</p>\n");
      out.write("                <p><strong>");
      out.print( idtype);
      out.write(" Number:</strong> ");
      out.print( idnum);
      out.write("</p>\n");
      out.write("                <p><strong>Designation:</strong> ");
      out.print( desig);
      out.write("</p>\n");
      out.write("                <p><strong>Salary:</strong> ");
      out.print( salary);
      out.write("</p>\n");
      out.write("                <p><strong>Current Address:</strong> ");
      out.print( cur_add);
      out.write("</p>\n");
      out.write("                <p><strong>Permanent Address:</strong> ");
      out.print( per_add);
      out.write("</p>\n");
      out.write("                <a class=\"cancel-button\" href=\"#\" onclick=\"closeManagerProfile()\" style=\"margin: auto\">Close</a>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"changePass\" class=\"section profile edit\">\n");
      out.write("                <h2>Change Password</h2>\n");
      out.write("                <form action=\"ManagerServlet?id=changePassword\" method=\"post\">\n");
      out.write("                    <p><strong>Username:</strong> <input type=\"text\" name=\"username\" value=\"");
      out.print( managerUsername);
      out.write("\" readonly></p>\n");
      out.write("                    <p><strong>Enter old password:</strong> <input type=\"password\" name=\"oldpass\"></p>\n");
      out.write("                    <p><strong>Enter new password:</strong> <input type=\"password\" id=\"newpass\" name=\"newpass\"></p>\n");
      out.write("                    <p><strong>Re-enter new password:</strong> <input type=\"password\" id=\"renewpass\" name=\"renewpass\" oninput=\"checkPass()\"></p>\n");
      out.write("                    <p id=\"incorrect\" style=\"color: red; font-size: 20px; display: none;\">Password must be same!</p>\n");
      out.write("                    <p id=\"correct\" style=\"color: lightgreen; font-size: 20px; display: none;\">Password matched!</p>\n");
      out.write("                    <button id=\"submit_btn\" type=\"submit\" style=\"display: none;\">Save</button>\n");
      out.write("                    <a class=\"cancel-button\" href=\"#\" onclick=\"checkPasswordMatch()\">Save</a>\n");
      out.write("                    <a class=\"cancel-button\" href=\"#\" onclick=\"closeManagerProfile()\">Cancel</a>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        <!-- All Actions Section -->\n");
      out.write("        \n");
      out.write("        <div id=\"actions\" class=\"section events\">\n");
      out.write("            \n");
      out.write("            <div id=\"all_projects\">\n");
      out.write("                <div class=\"heading\">\n");
      out.write("                <h2>Assigned Projects</h2>\n");
      out.write("            </div><br>\n");
      out.write("            ");

            List<ProjectObject> dataList = (List<ProjectObject>) request.getAttribute("dataList");
            for (ProjectObject data : dataList) {
        
      out.write("\n");
      out.write("           \n");
      out.write("            <div class=\"event\">\n");
      out.write("                ");

                    Blob posterBlob = data.getPhoto();
                    if (posterBlob != null) {
                        try (InputStream inputStream = posterBlob.getBinaryStream()) {
                            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                            byte[] buffer = new byte[4096];
                            int bytesRead = -1;
                            while ((bytesRead = inputStream.read(buffer)) != -1) {
                                outputStream.write(buffer, 0, bytesRead);
                            }
                            byte[] imageBytes = outputStream.toByteArray();
                            String base64Image = Base64.getEncoder().encodeToString(imageBytes);
                            out.println("<img src=\"data:image/jpeg;base64," + base64Image + "\" class=\"poster-image\">");
                        } catch (SQLException | IOException e) {
                            e.printStackTrace();
                        }
                    }
                
      out.write("\n");
      out.write("                <div class=\"msg-details\">\n");
      out.write("                    <div id=\"project_info_");
      out.print( data.getPid() );
      out.write("\" class=\"msg_info\">\n");
      out.write("                <h3 hidden>Project ID: p_");
      out.print( data.getPid() );
      out.write("</h3>\n");
      out.write("                <h3>Project Name: ");
      out.print( data.get_p_name() );
      out.write("</h3>\n");
      out.write("                    </div>\n");
      out.write("                        <div class=\"event-actions\">\n");
      out.write("                    <button id=\"viewbtn_");
      out.print( data.getPid() );
      out.write("\" onclick=\"viewProjectDetails(");
      out.print( data.getPid() );
      out.write(")\" style=\"display: block;\">View</button>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                 <form id=\"deleteEvent_");
      out.print( data.getPid() );
      out.write("\" action=\"Servlet?id=deleteEvent\" method=\"post\" style=\"display:none;\">\n");
      out.write("                    <input type=\"hidden\" name=\"eventID\" value=\"");
      out.print( data.getPid() );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"eventOrg\" value=\"");
      out.print( managerUsername );
      out.write("\">\n");
      out.write("                    <button id=\"deleteButton_");
      out.print( data.getPid() );
      out.write("\" type=\"submit\">Delete</button>\n");
      out.write("                </form>\n");
      out.write("                 <form id=\"viewEvent_");
      out.print( data.getPid() );
      out.write("\" action=\"#\" style=\"display:none;\">\n");
      out.write("                     <button id=\"viewButton_");
      out.print( data.getPid() );
      out.write("\" type=\"\" onclick=\"viewProjectDetails(");
      out.print( data.getPid() );
      out.write(")\">View</button>\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("            </div><br>\n");
      out.write("        \n");
      out.write("                ");

            }
        
      out.write("\n");
      out.write("            </div>\n");
      out.write("                \n");
      out.write("                <!-- PROJECT DETAILS Section -->\n");
      out.write("                \n");
      out.write("            ");

            List<ProjectObject> dataList1 = (List<ProjectObject>) request.getAttribute("dataList");
            for (ProjectObject data : dataList1) {
        
      out.write("\n");
      out.write("        <div id=\"project_detail_");
      out.print( data.getPid() );
      out.write("\" class=\"section events\" style=\"display: none;\">\n");
      out.write("            <div class=\"heading\">\n");
      out.write("                <h2>Project Details</h2>\n");
      out.write("            </div><br><br>\n");
      out.write("                <p hidden><strong>Client ID: c_</strong>");
      out.print( data.getCid() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Project Name: </strong>");
      out.print( data.get_p_name() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Start Date: </strong>");
      out.print( data.get_p_start_date() );
      out.write("</p><br>\n");
      out.write("                <p><strong>End Date (Estimated): </strong>");
      out.print( data.get_p_end_date() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Project Type: </strong>");
      out.print( data.get_p_type() );
      out.write("<p><br>\n");
      out.write("                <p><strong>Project Development Type: </strong>");
      out.print( data.get_p_dev_type() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Land Area: </strong>");
      out.print( data.get_p_land_area() );
      out.write(" Sq ft</p><br>\n");
      out.write("                <p><strong>Rate of Construction Cost: Rs.</strong>");
      out.print( data.get_p_rate() );
      out.write(" per Sq ft</p><br>\n");
      out.write("                <p><strong>Estimated Cost: Rs.</strong>");
      out.print( data.get_p_est_cost() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Project Location: </strong>");
      out.print( data.get_p_location() );
      out.write("</p><br>\n");
      out.write("                <div style=\"display: flex;\">\n");
      out.write("                    <form action=\"ManagerServlet?id=actionsPage\" method=\"post\" hidden>\n");
      out.write("                        <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( data.getPid() );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( data.get_p_name() );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( managerUsername );
      out.write("\">\n");
      out.write("                        <button id=\"takeAction_btn_");
      out.print( data.getPid() );
      out.write("\" type=\"submit\" style=\"margin: auto;\">Take Actions</button>\n");
      out.write("                    </form>\n");
      out.write("                    <button onclick=\"gotoTakeActionsPage(");
      out.print( data.getPid() );
      out.write(")\" style=\"margin: auto;\">Take Actions</button>\n");
      out.write("                    <button id=\"viewClient_");
      out.print( data.getCid() );
      out.write("\" onclick=\"viewClientDetails(");
      out.print( data.getCid() );
      out.write(',');
      out.write(' ');
      out.print( data.getPid() );
      out.write(")\" style=\"margin: auto;\">Client Details</button>\n");
      out.write("                    <button id=\"backbtn_");
      out.print( data.getPid() );
      out.write("\" onclick=\"back(");
      out.print( data.getPid() );
      out.write(")\" style=\"margin: auto;\">Back</button>\n");
      out.write("                </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("                ");

            }
        
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Client DETAILS Section -->\n");
      out.write("        \n");
      out.write("         ");

            List<ClientObject> client_dataList = (List<ClientObject>) request.getAttribute("client_dataList");
            for (ClientObject data : client_dataList) {
        
      out.write("\n");
      out.write("        \n");
      out.write("        <div id=\"client_detail_");
      out.print( data.getCid() );
      out.write("\" class=\"section events\" style=\"display: none;\">\n");
      out.write("            <div class=\"heading\">\n");
      out.write("                <h2>Client Details</h2>\n");
      out.write("            </div><br><br>\n");
      out.write("                <input id=\"pro_id\" type=\"hidden\" />\n");
      out.write("                <p hidden><strong>Client ID: c_</strong>");
      out.print( data.getCid() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Client Name: </strong>");
      out.print( data.getCname() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Email ID: </strong>");
      out.print( data.getCemail() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Mobile Number: </strong>");
      out.print( data.getCmobile() );
      out.write("</p><br>\n");
      out.write("                <p><strong>Address: </strong>");
      out.print( data.getCaddress() );
      out.write("<p><br>\n");
      out.write("                <button id=\"backbtn_");
      out.print( data.getCid() );
      out.write("\" onclick=\"backClient(");
      out.print( data.getCid() );
      out.write(")\" style=\"display: block;\">Back</button>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    \n");
      out.write("    function viewManagerProfile(){\n");
      out.write("        document.getElementById('view_manager_profile').style.display = \"flex\";\n");
      out.write("        document.getElementById('profile').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewChangePassForm(){\n");
      out.write("        document.getElementById('changePass').style.display = \"flex\";\n");
      out.write("        document.getElementById('profile').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function closeManagerProfile(){\n");
      out.write("        document.getElementById('view_manager_profile').style.display = \"none\";\n");
      out.write("        document.getElementById('changePass').style.display = \"none\";\n");
      out.write("        document.getElementById('profile').style.display = \"flex\";\n");
      out.write("    }\n");
      out.write("    function checkPass(){\n");
      out.write("        var pass1 = document.getElementById('newpass').value;\n");
      out.write("        var pass2 = document.getElementById('renewpass').value;\n");
      out.write("        if(pass1 === pass2){\n");
      out.write("            document.getElementById('correct').style.display = \"block\";\n");
      out.write("            document.getElementById('incorrect').style.display = \"none\";\n");
      out.write("        }\n");
      out.write("        else{\n");
      out.write("            document.getElementById('correct').style.display = \"none\";\n");
      out.write("            document.getElementById('incorrect').style.display = \"block\";\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    function checkPasswordMatch(){\n");
      out.write("        var pass1 = document.getElementById('newpass').value;\n");
      out.write("        var pass2 = document.getElementById('renewpass').value;\n");
      out.write("        if(pass1 === pass2){\n");
      out.write("            document.getElementById('submit_btn').click();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    function viewProjectDetails(pid){\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewClientDetails(cid, pid){\n");
      out.write("        document.getElementById(\"client_detail_\" + cid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("        \n");
      out.write("        var Pro_id = document.getElementById('pro_id');\n");
      out.write("        Pro_id.value = pid;\n");
      out.write("    }\n");
      out.write("    function back(pid){\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"block\";\n");
      out.write("    }\n");
      out.write("    function backClient(cid){\n");
      out.write("        var pid = document.getElementById('pro_id').value;\n");
      out.write("        document.getElementById(\"client_detail_\" + cid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function gotoTakeActionsPage(pid){\n");
      out.write("        document.getElementById('takeAction_btn_'+pid).click();\n");
      out.write("    }\n");
      out.write(" \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
