/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-19 10:53:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Base64;
import ServersidePackages.ProjectObject;
import ServersidePackages.ClientObject;
import ServersidePackages.EmployeeObject;
import ServersidePackages.VehicleObject;
import java.util.List;
import com.mysql.cj.jdbc.Blob;
import java.io.*;
import java.sql.*;

public final class projectactionsbysupervisor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ServersidePackages.ProjectObject");
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("ServersidePackages.EmployeeObject");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mysql.cj.jdbc.Blob");
    _jspx_imports_classes.add("ServersidePackages.VehicleObject");
    _jspx_imports_classes.add("ServersidePackages.ClientObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 String supervisorUsername = (String) request.getParameter("supervisor_username"); 
      out.write('\n');
 String projectID = (String) request.getParameter("project_id"); 
      out.write('\n');
 String projectName = (String) request.getParameter("project_name"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("     <head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("      <!--=============== FAVICON ===============-->\n");
      out.write("      <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("      <!--=============== REMIXICONS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.4.0/remixicon.css\" crossorigin=\"\">\n");
      out.write("      \n");
      out.write("      <!--=============== CSS ===============-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/organizerpage.css\">\n");
      out.write("\n");
      out.write("      <title>Supervisor Dashboard</title>\n");
      out.write("      <style>\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background: linear-gradient(to right bottom, #ffffff, #02effe);\n");
      out.write("            color: #fff;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .poster-image {\n");
      out.write("            width: 200px; /* Adjust width as needed */\n");
      out.write("            height: 250px; /* Auto adjust height to maintain aspect ratio */\n");
      out.write("        }\n");
      out.write("        .org_container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 100px auto;\n");
      out.write("            padding: 20px;\n");
      out.write("            display: grid;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("        .section {\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        h2 {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 20px;\n");
      out.write("            background: linear-gradient(to right bottom, #319da4c9, #3231a4);\n");
      out.write("            text-align: center;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 24px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .heading{\n");
      out.write("            height: min-content;\n");
      out.write("        }\n");
      out.write("        .action_btn{\n");
      out.write("            height: min-content;\n");
      out.write("            cursor: pointer;\n");
      out.write("            display: flex;\n");
      out.write("            \n");
      out.write("            h2{\n");
      out.write("                    background: linear-gradient(to right bottom, #45f0fbc9, #3231a4);\n");
      out.write("                    margin: auto;\n");
      out.write("                    width: 48%;\n");
      out.write("                    border-radius: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h2:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h3{\n");
      out.write("                    background: linear-gradient(to right bottom, #45f0fbc9, #3231a4);\n");
      out.write("                    margin: auto;\n");
      out.write("                    text-align: center;\n");
      out.write("                    font-weight: bold;\n");
      out.write("                    font-size: 24px;\n");
      out.write("                    padding: 20px;\n");
      out.write("                    border-radius: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            h3:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("            \n");
      out.write("            form{\n");
      out.write("                /*box-shadow: 0 0 0px 0 #ffffff;*/\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        /* Profile Section */\n");
      out.write("        .profile {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            padding: 40px;\n");
      out.write("            height: 730px;\n");
      out.write("            overflow: auto;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("            \n");
      out.write("            h2{\n");
      out.write("                background: linear-gradient(to right bottom, #319da4c9, #3231a4);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        .profile p {\n");
      out.write("            margin: 10px 0;\n");
      out.write("            font-size: 18px;\n");
      out.write("        }\n");
      out.write("        .profile button {\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .profile button:hover {\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .edit{\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("            .cancel-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                padding-top: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                padding-bottom: 7px;\n");
      out.write("                padding-left: 15px;\n");
      out.write("                padding-right: 15px;\n");
      out.write("                margin-left: 5px;\n");
      out.write("            }\n");
      out.write("            .cancel-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            .back-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                margin-left: 420px;\n");
      out.write("                width: 100px;\n");
      out.write("                height: 25px;\n");
      out.write("                position: fixed;\n");
      out.write("                margin-top: 650px;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .back-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            .logout-button{\n");
      out.write("                background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("                color: #fff;\n");
      out.write("                padding-top: 5px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                padding-bottom: 7px;\n");
      out.write("                padding-left: 15px;\n");
      out.write("                padding-right: 15px;\n");
      out.write("                margin-left: 5px;\n");
      out.write("                margin-top: 10px;\n");
      out.write("            }\n");
      out.write("            .logout-button:hover{\n");
      out.write("                background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("\n");
      out.write("        /* Events Section */\n");
      out.write("        .events {\n");
      out.write("            background: linear-gradient(to right bottom, #3231a4, #319da4c9);\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            padding: 20px;\n");
      out.write("            height: 730px;\n");
      out.write("            overflow-y: scroll;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("        }\n");
      out.write("        .event {\n");
      out.write("            background: linear-gradient(to right bottom, hsl(258.09deg 76.62% 70.36%), #dcacacba);\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("            cursor: pointer;\n");
      out.write("            position: relative;\n");
      out.write("            height: 290px;\n");
      out.write("            column-gap: 20px;\n");
      out.write("        }\n");
      out.write("        .event:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("        }\n");
      out.write("        .event h3 {\n");
      out.write("            margin: 0 0 10px;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("        .event p {\n");
      out.write("            margin: 5px 0;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        .event-info {\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\n");
      out.write("        }\n");
      out.write("        .msg-details{\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 40px 10px 10px 10px;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        .event-actions {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 10px;\n");
      out.write("            right: 10px;\n");
      out.write("            opacity: 0;\n");
      out.write("            transition: opacity 0.3s;\n");
      out.write("        }\n");
      out.write("        .event:hover .event-actions {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("        .event-actions button {\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 5px 10px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin: 5px 5px;\n");
      out.write("            width: 150px;\n");
      out.write("        }\n");
      out.write("        .event-actions button:hover {\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .event_form{\n");
      out.write("            margin: 10px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .post-button{\n");
      out.write("            background: linear-gradient(to right bottom, #00f0ff, #0018ff);\n");
      out.write("        }\n");
      out.write("        .post-button:hover{\n");
      out.write("            background: linear-gradient(to right bottom, #0018ff, #000000);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .msg-desc{\n");
      out.write("            height: 200px;\n");
      out.write("            overflow-y: scroll;\n");
      out.write("            scrollbar-width: none;\n");
      out.write("            text-align: justify;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .msg_info{\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("          .checkbox-wrapper-1 *,\n");
      out.write("  .checkbox-wrapper-1 ::after,\n");
      out.write("  .checkbox-wrapper-1 ::before {\n");
      out.write("    box-sizing: border-box;\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted {\n");
      out.write("    margin: 0;\n");
      out.write("    width: 0;\n");
      out.write("    height: 0;\n");
      out.write("    display: inline;\n");
      out.write("    -webkit-appearance: none;\n");
      out.write("    -moz-appearance: none;\n");
      out.write("    appearance: none;\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted + label:before {\n");
      out.write("    content: \"\";\n");
      out.write("    display: inline-block;\n");
      out.write("    vertical-align: top;\n");
      out.write("    height: 1.15em;\n");
      out.write("    width: 1.15em;\n");
      out.write("    margin-right: 0.6em;\n");
      out.write("    color: rgba(0, 0, 0, 0.275);\n");
      out.write("    border: solid 0.06em;\n");
      out.write("    box-shadow: 0 0 0.04em, 0 0.06em 0.16em -0.03em inset, 0 0 0 0.07em transparent inset;\n");
      out.write("    border-radius: 0.2em;\n");
      out.write("    background: url('data:image/svg+xml;charset=UTF-8,<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xml:space=\"preserve\" fill=\"white\" viewBox=\"0 0 9 9\"><rect x=\"0\" y=\"4.3\" transform=\"matrix(-0.707 -0.7072 0.7072 -0.707 0.5891 10.4702)\" width=\"4.3\" height=\"1.6\" /><rect x=\"2.2\" y=\"2.9\" transform=\"matrix(-0.7071 0.7071 -0.7071 -0.7071 12.1877 2.9833)\" width=\"6.1\" height=\"1.7\" /></svg>') no-repeat center, white;\n");
      out.write("    background-size: 0;\n");
      out.write("    will-change: color, border, background, background-size, box-shadow;\n");
      out.write("    transform: translate3d(0, 0, 0);\n");
      out.write("    transition: color 0.1s, border 0.1s, background 0.15s, box-shadow 0.1s;\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:enabled:active + label:before,\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:enabled + label:active:before {\n");
      out.write("    box-shadow: 0 0 0.04em, 0 0.06em 0.16em -0.03em transparent inset, 0 0 0 0.07em rgba(0, 0, 0, 0.1) inset;\n");
      out.write("    background-color: #f0f0f0;\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:checked + label:before {\n");
      out.write("    background-color: #3B99FC;\n");
      out.write("    background-size: 0.75em;\n");
      out.write("    color: rgba(0, 0, 0, 0.075);\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:checked:enabled:active + label:before,\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:checked:enabled + label:active:before {\n");
      out.write("    background-color: #0a7ffb;\n");
      out.write("    color: rgba(0, 0, 0, 0.275);\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:focus + label:before {\n");
      out.write("    box-shadow: 0 0 0.04em, 0 0.06em 0.16em -0.03em transparent inset, 0 0 0 0.07em rgba(0, 0, 0, 0.1) inset, 0 0 0 3.3px rgba(65, 159, 255, 0.55), 0 0 0 5px rgba(65, 159, 255, 0.3);\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:focus:active + label:before,\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:focus + label:active:before {\n");
      out.write("    box-shadow: 0 0 0.04em, 0 0.06em 0.16em -0.03em transparent inset, 0 0 0 0.07em rgba(0, 0, 0, 0.1) inset, 0 0 0 3.3px rgba(65, 159, 255, 0.55), 0 0 0 5px rgba(65, 159, 255, 0.3);\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted:disabled + label:before {\n");
      out.write("    opacity: 0.5;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark + label:before {\n");
      out.write("    color: rgba(255, 255, 255, 0.275);\n");
      out.write("    background-color: #222;\n");
      out.write("    background-image: url('data:image/svg+xml;charset=UTF-8,<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xml:space=\"preserve\" fill=\"rgba(34, 34, 34, 0.999)\" viewBox=\"0 0 9 9\"><rect x=\"0\" y=\"4.3\" transform=\"matrix(-0.707 -0.7072 0.7072 -0.707 0.5891 10.4702)\" width=\"4.3\" height=\"1.6\" /><rect x=\"2.2\" y=\"2.9\" transform=\"matrix(-0.7071 0.7071 -0.7071 -0.7071 12.1877 2.9833)\" width=\"6.1\" height=\"1.7\" /></svg>');\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark:enabled:active + label:before,\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark:enabled + label:active:before {\n");
      out.write("    background-color: #444;\n");
      out.write("    box-shadow: 0 0 0.04em, 0 0.06em 0.16em -0.03em transparent inset, 0 0 0 0.07em rgba(255, 255, 255, 0.1) inset;\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark:checked + label:before {\n");
      out.write("    background-color: #a97035;\n");
      out.write("    color: rgba(255, 255, 255, 0.075);\n");
      out.write("  }\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark:checked:enabled:active + label:before,\n");
      out.write("  .checkbox-wrapper-1 [type=checkbox].substituted.dark:checked:enabled + label:active:before {\n");
      out.write("    background-color: #c68035;\n");
      out.write("    color: rgba(0, 0, 0, 0.275);\n");
      out.write("  }\n");
      out.write("  .check_field{\n");
      out.write("      display: ruby;\n");
      out.write("  }\n");
      out.write("  .input-field{\n");
      out.write("      margin-top: 10px;\n");
      out.write("      margin-bottom: 10px;\n");
      out.write("      display: none;\n");
      out.write("      height: 250px;\n");
      out.write("      overflow-y: scroll;\n");
      out.write("  }\n");
      out.write("    </style>\n");
      out.write("   </head>\n");
      out.write("   \n");
      out.write("   <!--==================== HEADER ====================-->\n");
      out.write("      <header class=\"header\" id=\"header\">\n");
      out.write("        <nav class=\"nav container\">\n");
      out.write("            <a href=\"#\" class=\"nav__logo\">\n");
      out.write("                <img src=\"assets/img/logo.png\" alt=\"logo\">\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"nav__menu\" id=\"nav-menu\">\n");
      out.write("                <ul class=\"nav__list\">\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav__link\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav__link\">About</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"nav__item\">\n");
      out.write("                        <a href=\"contact.jsp\" class=\"nav__link\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("                <!--close button-->\n");
      out.write("                <div class=\"nav__close\" id=\"nav-close\">\n");
      out.write("                    <i class=\"ri-close-line\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--toggle button-->\n");
      out.write("            <div class=\"nav__toggle\" id=\"nav-toggle\">\n");
      out.write("                <i class=\"ri-menu-line\"></i>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("         \n");
      out.write("      </header>\n");
      out.write("    \n");
      out.write("   <div class=\"org_container\">\n");
      out.write("        <!-- Profile Section -->\n");
      out.write("        <div id=\"profile\" class=\"section profile\">\n");
      out.write("            <h3>Hello, ");
      out.print( supervisorUsername );
      out.write("!</h3><br>\n");
      out.write("            <a href=\"index.jsp\" class=\"logout-button\">Logout</a><br><br>\n");
      out.write("            <h2>");
      out.print( projectName );
      out.write("</h2><br>\n");
      out.write("    \n");
      out.write("    <br><br><h2>View Assigned Resources</h2><br><br>\n");
      out.write("    \n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewSupervisor()\">View Supervisor</a>    \n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewLabor()\">View Labors</a>\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewPlumber()\">View Plumbers</a>    \n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewElectrician()\">View Electricians</a>\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewCarpenter()\">View Carpenters</a>\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewPainter()\">View Painters</a>\n");
      out.write("    <a href=\"#\" class=\"logout-button\" onclick=\"viewVehicle()\">View Vehicles</a>\n");
      out.write("    \n");
      out.write("    <div id=\"View_supervisor\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Supervisor</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> emp_dataList2 = (List<EmployeeObject>) request.getAttribute("emp_dataList2");
            for (EmployeeObject data : emp_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_labors\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Labors</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> labor_dataList2 = (List<EmployeeObject>) request.getAttribute("labor_dataList2");
            for (EmployeeObject data : labor_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_electrician\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Electricians</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> ele_dataList2 = (List<EmployeeObject>) request.getAttribute("ele_dataList2");
            for (EmployeeObject data : ele_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_plumber\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Plumbers</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> plumber_dataList2 = (List<EmployeeObject>) request.getAttribute("plumber_dataList2");
            for (EmployeeObject data : plumber_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_carpenter\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Carpenters</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> carpenter_dataList2 = (List<EmployeeObject>) request.getAttribute("carpenter_dataList2");
            for (EmployeeObject data : carpenter_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_painter\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignEmployee\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Painter</label><br><br>\n");
      out.write("        ");

            List<EmployeeObject> painter_dataList2 = (List<EmployeeObject>) request.getAttribute("painter_dataList2");
            for (EmployeeObject data : painter_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getEid() );
      out.write("\" name=\"employee_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getEid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getEid() );
      out.write('"');
      out.write('>');
      out.print( data.getEname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"View_vehicle\" class=\"input-field\">\n");
      out.write("        <form action=\"ManagerServlet?id=assignVehicle\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"manager_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("        <label>Assigned Vehicles</label><br><br>\n");
      out.write("        ");

            List<VehicleObject> vehicle_dataList2 = (List<VehicleObject>) request.getAttribute("vehicle_dataList2");
            for (VehicleObject data : vehicle_dataList2) {
        
      out.write("\n");
      out.write("        <div class=\"checkbox-wrapper-1\">\n");
      out.write("            <input id=\"example-");
      out.print( data.getVid() );
      out.write("\" name=\"vehicle_id\" class=\"substituted\" type=\"checkbox\" value=\"");
      out.print( data.getVid() );
      out.write("\" aria-hidden=\"true\" style=\"display: none;\" />\n");
      out.write("            <label for=\"example-");
      out.print( data.getVid() );
      out.write('"');
      out.write('>');
      out.print( data.getVname() );
      out.write("</label>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("        <br><button type=\"submit\">Assign</button>\n");
      out.write("        <button type=\"reset\" onclick=\"cancelView()\">Cancel</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("         \n");
      out.write("        <br><br><h2>Daily Progress Report</h2><br><br> \n");
      out.write("        \n");
      out.write("        <form action=\"SupervisorServlet?id=uploadDailyReport\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("            \n");
      out.write("            <input type=\"hidden\" name=\"project_id\" value=\"");
      out.print( projectID );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"project_name\" value=\"");
      out.print( projectName );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"supervisor_username\" value=\"");
      out.print( supervisorUsername );
      out.write("\">\n");
      out.write("            \n");
      out.write("    <label for=\"date\">Date:</label>\n");
      out.write("    <input type=\"date\" id=\"date\" name=\"date\" required>\n");
      out.write("\n");
      out.write("    <label for=\"weather\">Weather Conditions:</label>\n");
      out.write("    <select id=\"weather\" name=\"weather\" required>\n");
      out.write("      <option value=\"\">Select weather conditions</option>\n");
      out.write("      <option value=\"sunny\">Sunny</option>\n");
      out.write("      <option value=\"cloudy\">Cloudy</option>\n");
      out.write("      <option value=\"rainy\">Rainy</option>\n");
      out.write("      <option value=\"windy\">Windy</option>\n");
      out.write("    </select>\n");
      out.write("    \n");
      out.write("    <label for=\"temperature\">Temperature (°C):</label>\n");
      out.write("    <input type=\"number\" id=\"temperature\" name=\"temperature\" required>\n");
      out.write("\n");
      out.write("    <label for=\"work-done\">Work Done:</label>\n");
      out.write("    <textarea id=\"work-done\" name=\"work-done\" rows=\"4\" required></textarea>\n");
      out.write("\n");
      out.write("    <label for=\"materials-used\">Materials Used:</label>\n");
      out.write("    <div id=\"materials-used\">\n");
      out.write("      <div>\n");
      out.write("        <input type=\"text\" name=\"material-name[]\" placeholder=\"Material Name\" required>\n");
      out.write("        <input type=\"number\" name=\"material-quantity[]\" placeholder=\"Quantity\" required>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <button type=\"button\" onclick=\"addMaterialField()\">Add Material</button>\n");
      out.write("\n");
      out.write("    <br><br><label for=\"equipment-used\">Equipment Used:</label>\n");
      out.write("    <div id=\"equipment-used\">\n");
      out.write("      <div>\n");
      out.write("        <input type=\"text\" name=\"equipment-name[]\" placeholder=\"Equipment Name\" required>\n");
      out.write("        <input type=\"number\" name=\"equipment-quantity[]\" placeholder=\"Quantity\" required>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <button type=\"button\" onclick=\"addEquipmentField()\">Add Equipment</button>\n");
      out.write("\n");
      out.write("    <br><br><label for=\"challenges\">Challenges Faced:</label>\n");
      out.write("    <textarea id=\"challenges\" name=\"challenges\" rows=\"4\"></textarea>\n");
      out.write("\n");
      out.write("    <label for=\"next-steps\">Next Steps:</label>\n");
      out.write("    <textarea id=\"next-steps\" name=\"next-steps\" rows=\"4\"></textarea>\n");
      out.write("    \n");
      out.write("    <label>Upload Photos of work done</label>\n");
      out.write("    <input type=\"file\" id=\"photos\" name=\"photos[]\" accept=\"image/*\" multiple />\n");
      out.write("\n");
      out.write("    <button type=\"submit\">Submit</button>\n");
      out.write("    <button type=\"reset\">Cancel</button>\n");
      out.write("  </form>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function viewUploadPhoto(){\n");
      out.write("        document.getElementById('upload_photo').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignSupervisor(){\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignLabor(){\n");
      out.write("        document.getElementById('assign_labors').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignVehicle(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignElectrician(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignPlumber(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"grid\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignCarpenter(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewAssignPainter(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"grid\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function cancelAssign(){\n");
      out.write("        document.getElementById('assign_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("        document.getElementById('upload_photo').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewSupervisor(){\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('assign_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewLabor(){\n");
      out.write("        document.getElementById('View_labors').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewVehicle(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewElectrician(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewPlumber(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"grid\";\n");
      out.write("    }\n");
      out.write("    function viewCarpenter(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewPainter(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"grid\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function cancelView(){\n");
      out.write("        document.getElementById('View_vehicle').style.display = \"none\";\n");
      out.write("        document.getElementById('View_labors').style.display = \"none\";\n");
      out.write("        document.getElementById('View_supervisor').style.display = \"none\";\n");
      out.write("        document.getElementById('View_carpenter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_painter').style.display = \"none\";\n");
      out.write("        document.getElementById('View_electrician').style.display = \"none\";\n");
      out.write("        document.getElementById('View_plumber').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewChangePassForm(){\n");
      out.write("        document.getElementById('changePass').style.display = \"flex\";\n");
      out.write("        document.getElementById('profile').style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function closeManagerProfile(){\n");
      out.write("        document.getElementById('view_manager_profile').style.display = \"none\";\n");
      out.write("        document.getElementById('changePass').style.display = \"none\";\n");
      out.write("        document.getElementById('profile').style.display = \"flex\";\n");
      out.write("    }\n");
      out.write("    function checkPass(){\n");
      out.write("        var pass1 = document.getElementById('newpass').value;\n");
      out.write("        var pass2 = document.getElementById('renewpass').value;\n");
      out.write("        if(pass1 === pass2){\n");
      out.write("            document.getElementById('correct').style.display = \"block\";\n");
      out.write("            document.getElementById('incorrect').style.display = \"none\";\n");
      out.write("        }\n");
      out.write("        else{\n");
      out.write("            document.getElementById('correct').style.display = \"none\";\n");
      out.write("            document.getElementById('incorrect').style.display = \"block\";\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    function checkPasswordMatch(){\n");
      out.write("        var pass1 = document.getElementById('newpass').value;\n");
      out.write("        var pass2 = document.getElementById('renewpass').value;\n");
      out.write("        if(pass1 === pass2){\n");
      out.write("            document.getElementById('submit_btn').click();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    function viewProjectDetails(pid){\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function viewClientDetails(cid, pid){\n");
      out.write("        document.getElementById(\"client_detail_\" + cid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("        \n");
      out.write("        var Pro_id = document.getElementById('pro_id');\n");
      out.write("        Pro_id.value = pid;\n");
      out.write("    }\n");
      out.write("    function back(pid){\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"block\";\n");
      out.write("    }\n");
      out.write("    function backClient(cid){\n");
      out.write("        var pid = document.getElementById('pro_id').value;\n");
      out.write("        document.getElementById(\"client_detail_\" + cid).style.display = \"none\";\n");
      out.write("        document.getElementById(\"project_detail_\" + pid).style.display = \"block\";\n");
      out.write("        document.getElementById(\"all_projects\").style.display = \"none\";\n");
      out.write("    }\n");
      out.write("    function gotoTakeActionsPage(){\n");
      out.write("        document.getElementById('takeAction_btn').click();\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function addMaterialField() {\n");
      out.write("      var materialsContainer = document.getElementById(\"materials-used\");\n");
      out.write("      var newMaterialField = document.createElement(\"div\");\n");
      out.write("      newMaterialField.innerHTML = '<input type=\"text\" name=\"material-name[]\" placeholder=\"Material Name\" required> <input type=\"number\" name=\"material-quantity[]\" placeholder=\"Quantity\" required>';\n");
      out.write("      materialsContainer.appendChild(newMaterialField);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function addEquipmentField() {\n");
      out.write("      var equipmentContainer = document.getElementById(\"equipment-used\");\n");
      out.write("      var newEquipmentField = document.createElement(\"div\");\n");
      out.write("      newEquipmentField.innerHTML = '<input type=\"text\" name=\"equipment-name[]\" placeholder=\"Equipment Name\" required> <input type=\"number\" name=\"equipment-quantity[]\" placeholder=\"Quantity\" required>';\n");
      out.write("      equipmentContainer.appendChild(newEquipmentField);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function getCurrentDate() {\n");
      out.write("      var today = new Date();\n");
      out.write("      var dd = String(today.getDate()).padStart(2, '0');\n");
      out.write("      var mm = String(today.getMonth() + 1).padStart(2, '0'); // January is 0!\n");
      out.write("      var yyyy = today.getFullYear();\n");
      out.write("\n");
      out.write("      return yyyy + '-' + mm + '-' + dd;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    document.getElementById(\"date\").value = getCurrentDate();\n");
      out.write(" \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
